import type { Metadata } from "next"
import "./globalStyles/normalize.css"
import "./globalStyles/globals.css"
import "./globalStyles/header.css"
import "./globalStyles/menu.css"
import Layout from "@/components/layouts/Layout";
import React from "react";

export const metadata: Metadata = {
  title: "Hazy Daisy Shop",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
